"""Tabular plugin: deep MVP modality for the DataForge AI compute plane."""

from app.plugins.tabular.imputation import (
    CANDIDATE_TABULAR_DATASET_KIND,
    CANDIDATE_TABULAR_DATASET_SCHEMA_VERSION,
    IMPUTATION_REPORT_KIND,
    IMPUTATION_REPORT_SCHEMA_VERSION,
    ExecuteTabularImputationRequest,
    ExecuteTabularImputationResult,
    ImputationExecutionError,
    execute_tabular_imputation_action,
)
from app.plugins.tabular.profile import (
    PROFILE_REPORT_FORMAT,
    PROFILE_REPORT_KIND,
    PROFILE_REPORT_MEDIA_TYPE,
    PROFILE_REPORT_SCHEMA_VERSION,
    BuildProfileResult,
    ProfileBuildRequest,
    build_tabular_profile_report,
    infer_tabular_profile,
)
from app.plugins.tabular.rules import (
    BusinessRule,
    BusinessRuleEvaluator,
    RuleFieldCheck,
    compute_rules_config_hash,
    parse_business_rules,
)
from app.plugins.tabular.splits import (
    DEFAULT_SPLIT_POLICY_VERSION,
    DEFAULT_SPLIT_RATIOS,
    SPLIT_MANIFEST_KIND,
    SPLIT_MANIFEST_SCHEMA_VERSION,
    ExecuteTabularSplitRequest,
    ExecuteTabularSplitResult,
    SplitCreationError,
    execute_tabular_split_action,
)

__all__ = [
    "BuildProfileResult",
    "CANDIDATE_TABULAR_DATASET_KIND",
    "CANDIDATE_TABULAR_DATASET_SCHEMA_VERSION",
    "DEFAULT_SPLIT_POLICY_VERSION",
    "DEFAULT_SPLIT_RATIOS",
    "BusinessRule",
    "BusinessRuleEvaluator",
    "PROFILE_REPORT_FORMAT",
    "PROFILE_REPORT_KIND",
    "PROFILE_REPORT_MEDIA_TYPE",
    "IMPUTATION_REPORT_KIND",
    "IMPUTATION_REPORT_SCHEMA_VERSION",
    "PROFILE_REPORT_SCHEMA_VERSION",
    "ExecuteTabularImputationRequest",
    "ExecuteTabularImputationResult",
    "ExecuteTabularSplitRequest",
    "ExecuteTabularSplitResult",
    "ImputationExecutionError",
    "ProfileBuildRequest",
    "SPLIT_MANIFEST_KIND",
    "SPLIT_MANIFEST_SCHEMA_VERSION",
    "SplitCreationError",
    "RuleFieldCheck",
    "build_tabular_profile_report",
    "execute_tabular_imputation_action",
    "execute_tabular_split_action",
    "compute_rules_config_hash",
    "infer_tabular_profile",
    "parse_business_rules",
]
