"""Privacy-safe logs, metrics, traces, and compute audit events."""

from app.telemetry.logging import (
    LogScannerResult,
    LogStatus,
    StructuredLogEvent,
    emit_structured_log,
    redact_for_logging,
    redact_text,
    scan_log_text,
)
from app.telemetry.metrics import (
    METRIC_AMBIGUOUS_OBJECT_COUNT,
    METRIC_ARTIFACT_READ_MS,
    METRIC_ARTIFACT_WRITE_MS,
    METRIC_EXPORT_BLOCKED_COUNT,
    METRIC_JOB_DURATION_MS,
    METRIC_JOB_FAILURE_COUNT,
    METRIC_PROBABLE_LABEL_ERROR_COUNT,
    METRIC_REVIEW_QUEUE_SIZE,
    CounterSnapshot,
    GaugeSnapshot,
    HistogramSnapshot,
    MetricsError,
    MetricsRegistry,
    MetricsSnapshot,
)
from app.telemetry.performance import (
    PerformanceReport,
    StageThreshold,
    StageThresholdViolation,
    StageTimer,
    StageTiming,
    StageTimingError,
    write_performance_report,
)
from app.telemetry.tracing import (
    SpanRecord,
    SpanStatus,
    TracingError,
    TracingRegistry,
)

__all__ = [
    "CounterSnapshot",
    "GaugeSnapshot",
    "HistogramSnapshot",
    "LogScannerResult",
    "LogStatus",
    "METRIC_AMBIGUOUS_OBJECT_COUNT",
    "METRIC_ARTIFACT_READ_MS",
    "METRIC_ARTIFACT_WRITE_MS",
    "METRIC_EXPORT_BLOCKED_COUNT",
    "METRIC_JOB_DURATION_MS",
    "METRIC_JOB_FAILURE_COUNT",
    "METRIC_PROBABLE_LABEL_ERROR_COUNT",
    "METRIC_REVIEW_QUEUE_SIZE",
    "MetricsError",
    "MetricsRegistry",
    "MetricsSnapshot",
    "PerformanceReport",
    "SpanRecord",
    "SpanStatus",
    "StageThreshold",
    "StageThresholdViolation",
    "StageTimer",
    "StageTiming",
    "StageTimingError",
    "StructuredLogEvent",
    "TracingError",
    "TracingRegistry",
    "emit_structured_log",
    "redact_for_logging",
    "redact_text",
    "scan_log_text",
    "write_performance_report",
]
